name: Rust

on: 
  push: 
    branches:
      - main
    paths:
      - "engine/**"
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
    paths: 
      - "engine/**"
  
  workflow_dispatch:
  
env:
  CARGO_TERM_COLOR: always
  
jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        working-directory: engine
        run: cargo fmt --check
  
  clippy: 
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        working-directory: engine
        run: cargo clippy -- -D warnings

  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Generate code coverage
        working-directory: engine
        run: cargo install cargo-tarpaulin && cargo tarpaulin --verbose --workspace
        
